"""
Cross-SDK parity: the Python SDK must produce byte-for-byte identical signed
output to the JS SDK.

The golden vector (tests/fixtures/js_parity_vector.json) is generated by the
*built JS SDK* — see js/scripts/gen-parity-vector.js. These tests re-sign the
same inputs with the same key at the same fixed timestamp and assert the
Python bytes + Ed25519 signatures match exactly, and that Python verifies the
JS-produced signatures. This is what guarantees notifications / key rotation /
views signed by either SDK are accepted by the same backend and renderer.

Run `node js/scripts/gen-parity-vector.js` to refresh after a JS signing change.
"""

import json
import os

import pytest

from yeriasdk import YeriaApp, YeriaAppConfig, Notification

FIXTURE = os.path.join(os.path.dirname(__file__), "fixtures", "js_parity_vector.json")


@pytest.fixture(scope="module")
def vector():
    with open(FIXTURE) as fh:
        return json.load(fh)


@pytest.fixture(scope="module")
def app(vector):
    return YeriaApp(
        YeriaAppConfig(
            app_id=vector["appId"],
            private_key=vector["privateKey"],
            public_key=vector["publicKey"],
        )
    )


def test_view_payload_bytes_match_js(app, vector):
    env = app._signer.sign_view(vector["viewJson"], vector["appId"], vector["timestamp"])
    assert env.payload == vector["viewPayload"]


def test_view_signature_matches_js(app, vector):
    env = app._signer.sign_view(vector["viewJson"], vector["appId"], vector["timestamp"])
    assert env.signature == vector["viewSignature"]


def test_python_verifies_js_view_signature(vector):
    assert (
        YeriaApp.verify_signature(
            vector["publicKey"], vector["viewPayload"], vector["viewSignature"]
        )
        is True
    )


def test_notification_signature_matches_js(app, vector):
    # No link -> JS omits the field entirely; Python must too (not "link":null).
    note = Notification("u1", "Title", "Body")
    signed = app._signer.sign_notification(note, vector["appId"], vector["timestamp"])
    assert signed.signature == vector["noteSignature"]


def test_accented_notification_signature_matches_js(app, vector):
    """Le backend reconstruit la charge utile d'une notification avec
    `JSON.stringify` avant d'en verifier la signature : un titre en francais
    signe par Python doit produire les memes octets que JS. `json.dumps`
    echappait le non-ASCII, donc la verification echouait."""
    note = Notification("u1", "Réservation confirmée ☕", "Votre créneau du 5 à 9 h — merci !")
    signed = app._signer.sign_notification(note, vector["appId"], vector["timestamp"])
    assert signed.signature == vector["noteAccentSignature"]


def test_boundary_float_payload_bytes_match_js(app, vector):
    """`1.0`, `1e-7`, `1e21`, `-0.0` : Python les ecrivait `1.0`, `1e-07`,
    `1e+21`, `-0.0` la ou JS ecrit `1`, `1e-7`, `1e+21`, `0`. Une latitude
    ronde suffisait a faire diverger la signature des deux SDK."""
    env = app._signer.sign_view(vector["floatViewJson"], vector["appId"], vector["timestamp"])
    assert env.payload == vector["floatPayload"]
    assert env.signature == vector["floatSignature"]
